#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

APP_NAME="rabbitmq"

app_version() {
 gc -am /sbin/apk list --installed --no-cache | /bin/grep "$APP_NAME" | /usr/bin/awk -F ' ' '{print $1}' | /usr/bin/awk -F '-' '{print $3}'
}

log "-i" "entrypoint" "Launch Application - $APP_NAME($(app_version))"
if [ -z "$@" ] ; then
 /usr/sbin/rabbitmq-server
 return 1
else
  log "-i" "entrypoint" "Launch Application [BACKGROUND]"
  /usr/sbin/rabbitmq-server -detached
  log "-i" "entrypoint" "Launch Application [WAIT(5s)]"
  /bin/sleep 5
return 0
fi
