#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

CONTAINER_NAME="rabbitmq"

app_version() {
 /usr/sbin/rabbitmqctl status | /bin/grep "version" | /usr/bin/awk -F ' ' '{print $3}'
}

if [ -z "$@" ] ; then
 /usr/sbin/rabbitmq-server
 return 1
else
 # ep_daemon_launch
 # export RABBITMQ_NODENAME="localhost"
  /usr/sbin/rabbitmq-server -detached
return 0
fi
